/* mac-geneva.js -- a Geneva for the strikes a translation adds to a file
   whose text draws in Geneva: the letters of one openly licensed Geneva 9
   recreation, and the widths of Apple's Geneva 9 and 10 from an openly
   licensed source, so that a strike made from them measures every string
   as Apple's does and no layout in the game moves.

   Loaded only when a translation is asked for (js/page-mechanics.js,
   spanishTable), since nothing else reads it. It is data and one reader;
   js/delv-translate.js (translateAddStrikes) builds the strikes.

   THE LETTERS. GENEVA9_TTF is "Geneva 9" by Kelsey Higham, the TrueType
   download of https://fontstruct.com/fontstructions/show/349277 unmodified
   (SHA-256 abda9418...8626, the same file as the systemless fork's
   fontstruct/geneva-9.ttf), under the Creative Commons Attribution 3.0
   licence; its licence and FontStruct's readme travel with it as
   res/Geneva9-LICENSE.txt and res/Geneva9-README.txt, and NOTICE says so.
   It is outlines on a grid of 64 units a square, sixteen squares an em, so
   drawn at a square a pixel it is the bitmap it was built from. It was
   chosen over its descendant Geneva 9.1 (res/Geneva9-1-Regular.woff2, the
   page's own face) for the fork on 17 September 2026 because it is the
   nearer to Apple's strike (the workbench's SYSTEMLESS-NOTES, "The
   recreations, measured against Apple's strikes"), and chosen again here
   by the maintainer on 29 September 2026 after a 10-point strike derived
   from it by adding a row was judged illegible: the 10-point strike draws
   the 9-point letters.

   THE WIDTHS. GENEVA_METRICS gives, for the 95 printable ASCII characters
   from the space, each one's advance and left bearing at 9 and at 10
   points, taken from the g! records of Kurrajong 9 and Kurrajong 10,
   Copyright (c) 2026 Ben Letchford, SIL Open Font License 1.1, Reserved
   Font Name "Systemless" (the systemless repository at commit 0540ef82,
   src/quickdraw/fonts/pixel_font/geneva9.rs and geneva10.rs), whose
   metrics were conformed to Apple's strikes so text lays out identically;
   the fork's compatibility/geneva9-advances.bin is the same 9-point
   advances. Measured against Apple's Geneva on 29 September 2026: all 95
   advances at both sizes equal, the bearings all but i and l (and ^ and y
   at 10), which moves where a letter's ink sits and never a width. The
   10-point bearings place Geneva 10's own, wider letters, so the 10-point
   strike does not use them as they are: it says only which side of Geneva
   9's letter an odd pixel of extra width goes (js/delv-translate.js).
   Only the numbers are here; Kurrajong's pixels are not. res/Kurrajong-OFL.txt
   is the licence. The frame is Geneva's at both sizes, ten pixels above
   the baseline and two below, with one of leading at 10 points; an
   accented letter takes its letter's width, as Apple's do. */
const GENEVA9_TTF =
  'AAEAAAALAIAAAwAwRFNJRwAAAAEAAHQMAAAACE9TLzJiuGKNAAABOAAAAGBjbWFw35wm0gAABDgAAASUZ2x5Zg5CsogAAAtwAABN' +
  'yGhlYWQulxoIAAAAvAAAADZoaGVhBIICaQAAAPQAAAAkaG10eOdYCIAAAAGYAAACoGxvY2EAGSZ4AAAIzAAAAqRtYXhwALcAOgAA' +
  'ARgAAAAgbmFtZSamxeYAAFk4AAAas3Bvc3QAaQAzAABz7AAAACAAAQAAAAEAADtx9ftfDzz1AAAEAAAAAADmwWuFAAAAAObBa4UA' +
  'AP+AAgACgAAAAAgAAgABAAAAAAABAAACgP+AAAACQAAAAAACAAABAAAAAAAAAAAAAAAAAAAAqAABAAAAqAA4AA4AAAAAAAIAAAAA' +
  'AAAAAAAAAAAAAAAAAAIBYAGQAAUABAIAAgAAAP/AAgACAAAAAgAAMwDMAAAAAAQAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAEZTVFIA' +
  'QAAgISIBwP+AAAACgACAIAEB/83/AAABQAHAAAAAIAAAAZgAAADAAAAAwABAAUAAQAHAAEABgAAAAkAAAAIAAAAAwABAAQAAAAEA' +
  'AAABwABAAYAAAAEAAEABQAAAAMAAQAGAAEABgAAAAYAAQAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAMAAQAEAAEAB' +
  'QABAAYAAAAFAAEABgABAAgAAAAHAAEABgAAAAYAAAAGAAAABQAAAAUAAAAGAAAABgAAAAMAAQAGAAAABgAAAAUAAAAIAAAABgAAA' +
  'AYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAACAAAAAYAAAAGAAAABgAAAAQAAQAGAAEABAABAAQAAAAGAAAAAwAAAAUAA' +
  'AAFAAAABQAAAAUAAAAFAAAABAAAAAUAAAAFAAAAAwAAAAQAAAAFAAAAAwAAAAgAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAEA' +
  'AAABQAAAAYAAAAIAAAABgAAAAYAAAAFAAAABAAAAAIAAAAEAAAABgAAAAYAAAADAAEABgAAAAYAAAAGAAAABgAAAAQAAAAJAAAAB' +
  'QAAAAgAAAAGAAEACQAAAAUAAAAGAAAABAABAAYAAAAGAAAABAABAAUAAAAIAAEABgABAAcAAQAHAAEABwABAAkAAAAGAAAABQAAA' +
  'AYAAAAGAAAABwAAAAYAAAAGAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAACQABAAUAAAAFAAAABQAAAAUAAAAFAAAAAwAAAAMAA' +
  'AAEAAAABAAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAYAAAAGAAAABQAAAAUAAAAFAAAABQAAAAYAAAAGAAAABQAAAAcAAAAEA' +
  'AEABAABAAcAAQAHAAIABAAAAAYAAAAIAAAACQAAAAAAAAgAAAAMAAAAUAAMAAQAAAlQABAJAAAAAOAAgAAQAGAB+AKMApQCsAK4A' +
  'sQC2ALgAuwDAAMcAyQDRANYA2ADcAO8A/AD/AW8gFCAZIB0gICAiICYhIv//AAAAIACgAKUApwCuALAAtAC4ALoAvwDEAMkA0QDW' +
  'ANgA3ADfAPEA/wFuIBQgGCAcICAgIiAmISL////h/8D/v/++/73/vP+6/7n/uP+1/7L/sf+q/6b/pf+i/6D/n/+d/y/gi+CI4Ibg' +
  'hOCD4IDfhQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAJAAAAAOAAgAAQAGAB+AKMApQCsAK4AsQC2ALgAuwDAAMcAyQDRANYA2ADcAO8A' +
  '/AD/AW8gFCAZIB0gICAiICYhIv//AAAAIACgAKUApwCuALAAtAC4ALoAvwDEAMkA0QDWANgA3ADfAPEA/wFuIBQgGCAcICAgIiAm' +
  'ISL////h/8D/v/++/73/vP+6/7n/uP+1/7L/sf+q/6b/pf+i/6D/n/+d/y/gi+CI4IbghOCD4IDfhQABAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAaAAAAGgAAACgAAAA2AAAAYgAAAJ8AAADlAAABNQAAAT4AAAFdAAABfAAAAaUAAAG4AAABxgAAAc8AAAHYAAAB8QA' +
  'AAgoAAAIYAAACQQAAAmoAAAKKAAACqAAAAswAAALiAAADDAAAAzAAAAM+AAADUgAAA3EAAAN/AAADngAAA8IAAAP+AAAEGwAABDk' +
  'AAARYAAAEdgAABIkAAASZAAAEugAABM0AAATWAAAE6gAABRkAAAUkAAAFTQAABWgAAAWBAAAFlwAABbgAAAXeAAAGCAAABhYAAAY' +
  'qAAAGSQAABnMAAAaoAAAGxwAABusAAAb5AAAHEgAAByAAAAc0AAAHPQAAB0sAAAdmAAAHfAAAB5sAAAexAAAHzAAAB+QAAAf/AAA' +
  'IEgAACCMAAAg3AAAIWwAACGYAAAiCAAAIkwAACKwAAAjCAAAI2AAACOsAAAkKAAAJIgAACTMAAAlSAAAJfAAACbEAAAnKAAAJ5QA' +
  'ACgQAAAoNAAAKLAAACkUAAApFAAAKUwAACoAAAAqjAAAK0AAACwoAAAsYAAALWAAAC3EAAAurAAALtgAAC/0AAAwWAAAMLgAADDw' +
  'AAAxVAAAMdQAADIMAAAyiAAAM3AAADQAAAA0oAAANUAAADYMAAA2qAAAN0wAADfEAAA4iAAAORgAADnoAAA6ZAAAOvQAADtsAAA7' +
  '5AAAPHQAAD0YAAA9kAAAPjQAAD60AAA/UAAAP+gAAECAAABBMAAAQcgAAEIgAABCeAAAQugAAENAAABD3AAARGwAAET8AABFpAAA' +
  'RmAAAEbwAABHQAAAR/gAAEhoAABI2AAASVwAAEnMAABKXAAASqwAAErwAABLFAAAS0wAAEuEAABL6AAATEwAAEyYAABM5AAATTQA' +
  'AE3IAAUAAAAAAVgBwAACAAUACAALAA8AAAEBAQEBAQEBAQEBAQEBAQEBE/+Z/5n/7QBn/5kA9AAA/5n/7QBn/zL/uwAAAVgAAAAy' +
  'AJr/ZgATAJsAmv7LATX/ZgATAJsAAP5yAcAAAP5AAAAAAgBAAAAAgAHAAAMABwAAAQEBAQEBAQEAQAAAAEAAAP/AAAAAQAAAAAAA' +
  'QAAA/8AAgAFAAAD+wAACAEABQAEAAcAAAwAHAAABAQEBAQEBAQBAAAAAQAAAAEAAAABAAAABQACAAAD/gAAAAIAAAP+AAAIAQADA' +
  'AYACAAADAB8AAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAP/AAAD/wAAA/8AAAABAAAD/wAAAAEAAAABAAAAA' +
  'QAAAAEAAAABAAAD/wAAAAEAAAP/AAAD/wAAA/8AAAAFAAEAAAP/A/4AAQAAAAEAAAABAAAAAQAAAAEAAAP/AAAAAQAAA/8AAAP/A' +
  'AAD/wAAA/8AAAP/AAAAAQAAA/8AABQAA/8ABQAIAAAMABwALAA8AKwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEAAAAAAEAAAADAAAAAQAAA/sAAAABAAAAAwAAAAEAAAP9AAAD/wAAAAEAAAP/AAAAAQAAA/8AAAABAAAAAQAAA' +
  'AEAAAP/AAAAAQAAA/8AAAABAAAD/wAAAAEAAQAAA/8AAAACAAAD/gADAAIAAAP+AAEAAQAAA/8D+gABAAAAAQAAAAIAAAABAAAAA' +
  'gAAAAEAAAABAAAD/wAAA/8AAAP+AAAD/wAAA/4AAAP/AAAD/wAAAAAgAAAAAAgABwAADAAcACwAPABMAIQAlADEAAAEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAABAAAAAwAAAAIAAAP7AAAAAQAAAAQAAAABAAAD+' +
  'QAAAAIAAAABAAAD/wAAAAEAAAABAAAAAQAAAAEAAAP+AAAD+wAAAAEAAAACAAAD/gAAAAcAAAP/AAAD/wAAA/4AAAAAAAEAAAP/A' +
  'AAAAQAAA/8AAQABAAAD/wAAAAIAAAP+AAIAAQAAA/8D/gABAAAAAQAAAAEAAAABAAAD/wAAA/8AAAP+AAMAAgAAA/4AAAACAAAAA' +
  'QAAA/8AAAP/AAAAAQAAA/4AAAAAOAAAAAAHAAgAAAwAHAAsADwATABcAGwAfACMAJwArAC8AMwA3AAABAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAAAMAAAABAAAD/AAAAAEAAAABAAAAAQAAA/oAA' +
  'AABAAAAAwAAAAEAAAP8AAAAAQAAAAEAAAABAAAAAQAAAAEAAAP8AAAAAQAAAAAAAAABAAAD/QAAAAEAAAACAAAAAQAAA/0AAAACA' +
  'AAAAAABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAAABAAAD/wAAAAIAAAP+AAEAAQAAA/8AAQABAAAD/wAAAAEAAAP/AAAAAQAAA/8AA' +
  'QABAAAD/wABAAEAAAP/AAAAAgAAA/4AAQABAAAD/wABAAEAAAP/AAAEAQAFAAIABwAADAAABAQEBAEAAAABAAAABQACAAAD/gAAA' +
  'AAUAAP/AAMACAAADAAcACwAPABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAIAAAABAAAD/gAAAAEAAAP+AAAAAQAAAAAAAAABAAAAA' +
  'AAAAAEAAAP/AAEAAAP/AAEAAQAAA/8AAQAFAAAD+wAFAAEAAAP/AAEAAQAAA/8AAAAAFAAD/wADAAgAAAwAHAAsADwATAAABAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAP+AAAAAQAAA/4AAAABAAAD/wABAAAD/wABAAEAAAP/AAEAB' +
  'QAAA/sABQABAAAD/wABAAEAAAP/AAAAABQBAAIABgAHAAAMABwATABcAGwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQCA' +
  'AAAAQAAAAEAAAABAAAD/gAAA/4AAAACAAAAAQAAAAIAAAP+AAAD/gAAAAEAAAABAAAAAQAAAAIAAQAAA/8AAAABAAAD/wABAAEAA' +
  'AABAAAAAQAAA/8AAAP/AAAD/wADAAEAAAP/AAAAAQAAA/8AAAAABAAAAQAFAAYAACwAAAQEBAQEBAQEBAQEBAIAAAP+AAAAAgAAA' +
  'AEAAAACAAAD/gAAAAEAAgAAAAEAAAACAAAD/gAAA/8AAAP+AAAAAAgBA/4AAwABAAAMABwAAAQEBAQEBAQEAQAAAAEAAAAAAAAAA' +
  'QAAA/4AAQAAA/8AAQACAAAD/gAABAAAAwAEAAQAAAwAAAQEBAQAAAAABAAAAAMAAQAAA/8AAAAABAEAAAACAAEAAAwAAAQEBAQBA' +
  'AAAAQAAAAAAAQAAA/8AAAAAEAEAAAAFAAgAAAwAHAAsADwAAAQEBAQEBAQEBAQEBAQEBAQBAAAAAQAAAAAAAAABAAAAAAAAAAEAA' +
  'AAAAAAAAQAAAAAAAgAAA/4AAgACAAAD/gACAAIAAAP+AAIAAgAAA/4AABAAAAAABQAHAAAMABwALAA8AAAEBAQEBAQEBAQEBAQEB' +
  'AQEAQAAAAMAAAP8AAAAAQAAAAMAAAABAAAD/AAAAAMAAAAAAAEAAAP/AAEABQAAA/sAAAAFAAAD+wAFAAEAAAP/AAAEAQAAAAMAB' +
  'wAAHAAABAQEBAQEBAQCAAAD/wAAAAEAAAABAAAAAAAFAAAAAQAAAAEAAAP5AAAAABgAAAAABQAHAAAcACwAPABMAFwAbAAABAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAABAAAAAQAAAAMAAAP9AAAAAQAAAAAAAAABAAAD/AAAAAEAAAADAAAAAQAAA/wAA' +
  'AADAAAAAAABAAAAAQAAA/8AAAP/AAIAAQAAA/8AAQABAAAD/wACAAEAAAP/A/8AAgAAA/4AAgABAAAD/wAAFAAAAAAFAAcAAAwAH' +
  'AAsAEwAbAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAADAAAD/AAAAAEAAAADAAAAAQAAA/wAAAABAAAAAQAAAAEAA' +
  'AP/AAAD/QAAAAUAAAP/AAAAAAABAAAD/wABAAEAAAP/AAAAAgAAA/4AAgABAAAAAQAAA/8AAAP/AAIAAQAAAAEAAAP/AAAD/wAAA' +
  'AAIAAAAAAUABwAADABUAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAEAAAABAAAD/QAAAAEAAAACAAAD/wAAAAEAAAABAAAAA' +
  'QAAA/8AAAAEAAEAAAP/A/wAAgAAAAIAAAP/AAAAAgAAAAEAAAABAAAD/AAAA/8AAAP+AAAAABAAAAAABQAHAAAMABwALABMAAAEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAEAAAADAAAD/AAAAAEAAAADAAAAAQAAA/sAAAAFAAAD/AAAAAMAAAAAAAEAAAP/AAEAAQAAA/8AA' +
  'AADAAAD/QADAAMAAAP/AAAD/wAAA/8AABQAAAAABQAHAAAMABwAPABMAFwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAADA' +
  'AAAAAAAAAEAAAP7AAAAAQAAAAMAAAP9AAAAAAAAAAEAAAAAAAAAAgAAAAAAAQAAA/8AAQACAAAD/gAAAAQAAAP/AAAD/wAAA/4AB' +
  'AABAAAD/wABAAEAAAP/AAAAAAwAAAAABQAHAAAMABwANAAABAQEBAQEBAQEBAQEBAQCAAAAAQAAAAAAAAABAAAAAAAAA/wAAAAFA' +
  'AAAAAADAAAD/QADAAIAAAP+AAIAAQAAAAEAAAP+AAAcAAAAAAUABwAADAAcACwAPABMAFwAbAAABAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAEAAAADAAAD/AAAAAEAAAADAAAAAQAAA/wAAAADAAAD/AAAAAEAAAADAAAAAQAAA/wAAAADAAAAAAABAAAD/wABA' +
  'AIAAAP+AAAAAgAAA/4AAgABAAAD/wABAAIAAAP+AAAAAgAAA/4AAgABAAAD/wAAAAAUAAAAAAUABwAADAAcACwATABcAAAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAAAAAAAABAAAD/AAAAAEAAAADAAAD/QAAAAMAAAABAAAD/AAAAAMAAAAAAAEAAAP/A' +
  'AEAAQAAA/8AAwACAAAD/gP+AAEAAAABAAAAAgAAA/wABAABAAAD/wAAAAAIAQAAAAIABQAADAAcAAAEBAQEBAQEBAEAAAABAAAD/' +
  'wAAAAEAAAAAAAEAAAP/AAQAAQAAA/8AAAwBA/4AAwAFAAAMABwALAAABAQEBAQEBAQEBAQEAQAAAAEAAAAAAAAAAQAAA/8AAAABA' +
  'AAD/gABAAAD/wABAAIAAAP+AAUAAQAAA/8AAAAAFAEAAQAEAAYAAAwAHAAsADwATAAABAQEBAQEBAQEBAQEBAQEBAQEBAQDAAAAA' +
  'QAAA/4AAAABAAAD/gAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAQABAAAD/wABAAEAAAP/AAEAAQAAA/8AAQABAAAD/wABAAEAAAP/A' +
  'AAAAAgAAAIABQAFAAAMABwAAAQEBAQEBAQEAAAAAAUAAAP7AAAABQAAAAIAAQAAA/8AAgABAAAD/wAAFAEAAQAEAAYAAAwAHAAsA' +
  'DwATAAABAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAQAAAAAAAAABAAAAAAAAAAEAAAP+AAAAAQAAA/4AAAABAAAAAQABAAAD/wABA' +
  'AEAAAP/AAEAAQAAA/8AAQABAAAD/wABAAEAAAP/AAAAABgBAAAABQAHAAAMABwALAA8AEwAXAAABAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEAgAAAAEAAAP/AAAAAQAAAAAAAAABAAAD/QAAAAEAAAACAAAAAQAAA/0AAAACAAAAAAABAAAD/wACAAEAAAP/AAEAAQAAA' +
  '/8AAgABAAAD/wP/AAIAAAP+AAIAAQAAA/8AACQAA/8ABwAHAAAMABwALAA8AGQAdACEAJQApAAABAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAgAAAAMAAAP8AAAAAQAAAAAAAAABAAAD/QAAAAEAAAACAAAAAQAAA/8AAAACAAAAAQAAA' +
  'AAAAAABAAAD+gAAAAEAAAADAAAAAQAAA/wAAAADAAAD/wABAAAD/wABAAEAAAP/AAIAAgAAA/4D/wAEAAAD/AAAAAEAAAACAAAAA' +
  'QAAA/0AAAP/AAEAAwAAA/0AAwABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAAgBAAAABgAHAAA8AEwAAAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEAQAAAAEAAAABAAAAAQAAAAEAAAABAAAD/wAAA/0AAAABAAAAAQAAAAAAAwAAAAIAAAP+AAAAAgAAA/4AAAP9AAAAAgAAA/4AB' +
  'QACAAAD/gAADAAAAAAFAAcAAAwAHABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAABAAAD/wAAAAEAAAP7AAAABAAAA/0AAAADA' +
  'AAD/QAAAAMAAAABAAIAAAP+AAMAAgAAA/4D/AAHAAAD/wAAA/4AAAP/AAAD/gAAA/8AAAAAFAAAAAAFAAcAAAwAHAAsADwATAAAB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAwAAAAAAAAABAAAD+wAAAAEAAAADAAAAAQAAA/wAAAADAAAAAAABAAAD/wABAAEAAAP/A' +
  'AAABQAAA/sABAABAAAD/wABAAEAAAP/AAAAABAAAAAABQAHAAAMABwALABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAMAAAABAAAAA' +
  'AAAAAEAAAP+AAAAAQAAA/wAAAADAAAD/gAAAAIAAAABAAEAAAP/AAEAAwAAA/0AAwABAAAD/wP7AAcAAAP/AAAD+wAAA/8AAAQAA' +
  'AAABAAHAAAsAAAEBAQEBAQEBAQEBAQAAAAABAAAA/0AAAACAAAD/gAAAAMAAAAAAAcAAAP/AAAD/gAAA/8AAAP+AAAD/wAAAAAEA' +
  'AAAAAQABwAAJAAABAQEBAQEBAQEBAAAAAAEAAAD/QAAAAIAAAP+AAAAAAAHAAAD/wAAA/4AAAP/AAAD/QAAFAAAAAAFAAcAAAwAJ' +
  'AA0AEQAVAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAADAAAAAAAAA/8AAAACAAAD+wAAAAEAAAADAAAAAQAAA/wAAAADAAAAA' +
  'AABAAAD/wABAAIAAAABAAAD/QAAAAUAAAP7AAQAAQAAA/8AAQABAAAD/wAABAAAAAAFAAcAACwAAAQEBAQEBAQEBAQEBAAAAAABA' +
  'AAAAwAAAAEAAAP/AAAD/QAAAAAABwAAA/0AAAADAAAD+QAAAAMAAAP9AAAAAAQBAAAAAgAHAAAMAAAEBAQEAQAAAAEAAAAAAAcAA' +
  'AP5AAAAAAwAAAAABQAHAAAMABwALAAABAQEBAQEBAQEBAQEAQAAAAMAAAP8AAAAAQAAAAMAAAABAAAAAAABAAAD/wABAAIAAAP+A' +
  'AAABgAAA/oAAAAAHAAAAAAFAAcAAAwAHAAsADwATABsAHwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAEAA' +
  'AP+AAAAAQAAA/4AAAABAAAD/wAAAAEAAAAAAAAAAQAAA/wAAAABAAAAAQAAA/8AAAADAAAAAQAAAAAAAQAAA/8AAQABAAAD/wABA' +
  'AEAAAP/AAIAAQAAA/8AAQABAAAD/wP7AAcAAAP9AAAD/wAAA/0ABgABAAAD/wAAAAAEAAAAAAQABwAAFAAABAQEBAQEAAAAAAEAA' +
  'AADAAAAAAAHAAAD+gAAA/8AABQAAAAABwAHAAAMABwALABMAGwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQDAAAAAQAAA' +
  '/4AAAABAAAAAQAAAAEAAAP7AAAAAQAAAAEAAAP/AAAABQAAA/8AAAABAAAAAQAAAAMAAQAAA/8AAQABAAAD/wAAAAEAAAP/A/wAB' +
  'wAAA/8AAAP/AAAD+wAAAAUAAAABAAAAAQAAA/kAAAAADAAAAAAFAAcAAAwAJABEAAAEBAQEBAQEBAQEBAQEBAQEBAQCAAAAAQAAA' +
  '/0AAAACAAAD/wAAAAMAAAP/AAAAAQAAAAEAAAADAAIAAAP+A/0ABwAAA/4AAAP7AAAAAQAAAAIAAAAEAAAD+QAAEAAAAAAFAAcAA' +
  'AwAHAAsADwAAAQEBAQEBAQEBAQEBAQEBAQBAAAAAwAAA/wAAAABAAAAAwAAAAEAAAP8AAAAAwAAAAAAAQAAA/8AAQAFAAAD+wAAA' +
  'AUAAAP7AAUAAQAAA/8AAAgAAAAABQAHAAAMADQAAAQEBAQEBAQEBAQEBAQEBAAAAAEAAAP7AAAABAAAA/0AAAADAAAD/QAAAAQAA' +
  'gAAA/4D/AAHAAAD/wAAA/4AAAP/AAAD/QAAAAAQAAP/AAUABwAAJAA0AEQAVAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAMAAAP+A' +
  'AAAAQAAAAEAAAABAAAD/AAAAAEAAAADAAAAAQAAA/wAAAADAAAD/wABAAAAAQAAAAEAAAP/AAAD/gACAAUAAAP7AAAABQAAA/sAB' +
  'QABAAAD/wAAAAAQAAAAAAUABwAADAAcACwAZAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAQAAA/4AAAABAAAAAAAAA' +
  'AEAAAP7AAAABAAAA/0AAAADAAAD/wAAA/8AAAP/AAAAAAABAAAD/wABAAEAAAP/AAMAAgAAA/4D/AAHAAAD/wAAA/4AAAP/AAAD/' +
  'wAAAAEAAAP9AAAAABwAAAAABQAHAAAMABwALAA8AEwAXABsAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAMAAAP8A' +
  'AAAAQAAAAMAAAABAAAD/AAAAAMAAAP8AAAAAQAAAAMAAAABAAAD/AAAAAMAAAAAAAEAAAP/AAEAAQAAA/8AAAACAAAD/gACAAEAA' +
  'AP/AAEAAgAAA/4AAQABAAAD/wABAAEAAAP/AAAAAAQAAAAABQAHAAAcAAAEBAQEBAQEBAIAAAP+AAAABQAAA/4AAAAAAAYAAAABA' +
  'AAD/wAAA/oAAAAADAAAAAAFAAcAAAwAHAAsAAAEBAQEBAQEBAQEBAQBAAAAAwAAA/wAAAABAAAAAwAAAAEAAAAAAAEAAAP/AAEAB' +
  'gAAA/oAAAAGAAAD+gAAAAAUAAAAAAUABwAADAAcACwAPABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAIAAAABAAAD/gAAAAEAAAABA' +
  'AAAAQAAA/wAAAABAAAAAwAAAAEAAAAAAAIAAAP+AAIAAgAAA/4AAAACAAAD/gACAAMAAAP9AAAAAwAAA/0AAAAAHAAAAAAHAAcAA' +
  'AwAHAAsADwATABcAGwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQCAAAAAQAAAAEAAAABAAAD/AAAAAEAAAABAAAAAQAAA' +
  'AEAAAABAAAD+gAAAAEAAAAFAAAAAQAAAAAAAwAAA/0AAAADAAAD/QADAAIAAAP+AAAAAgAAA/4AAAACAAAD/gACAAIAAAP+AAAAA' +
  'gAAA/4AAAAAJAAAAAAFAAcAAAwAHAAsADwATABcAGwAfACMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAA' +
  'AAAAQAAAAMAAAABAAAD/AAAAAEAAAABAAAAAQAAA/4AAAABAAAD/gAAAAEAAAABAAAAAQAAA/wAAAABAAAAAwAAAAEAAAAAAAIAA' +
  'AP+AAAAAgAAA/4AAgABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAQABAAAD/wAAAAEAAAP/AAEAAgAAA/4AAAACAAAD/gAAAAAUAAAAA' +
  'AUABwAADAAcACwAPABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAIAAAABAAAD/gAAAAEAAAABAAAAAQAAA/wAAAABAAAAAwAAAAEAA' +
  'AAAAAQAAAP8AAQAAQAAA/8AAAABAAAD/wABAAIAAAP+AAAAAgAAA/4AAAAAFAAAAAAFAAcAABQAJAA0AEQAXAAABAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEAAAAAAEAAAAEAAAD/AAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAA/wAAAAFAAAAAAACAAAD/wAAA/8AA' +
  'gABAAAD/wABAAEAAAP/AAEAAQAAA/8AAQABAAAAAQAAA/4AAAAABAED/wADAAgAABwAAAQEBAQEBAQEAQAAAAIAAAP/AAAAAQAAA' +
  '/8ACQAAA/8AAAP5AAAD/wAAAAAQAQAAAAUACAAADAAcACwAPAAABAQEBAQEBAQEBAQEBAQEBAQAAAABAAAD/gAAAAEAAAP+AAAAA' +
  'QAAA/4AAAABAAAAAAACAAAD/gACAAIAAAP+AAIAAgAAA/4AAgACAAAD/gAABAED/wADAAgAABwAAAQEBAQEBAQEAQAAAAEAAAP/A' +
  'AAAAgAAA/8AAQAAAAcAAAABAAAD9wAAAAAMAAAFAAMABwAADAAcACwAAAQEBAQEBAQEBAQEBAAAAAABAAAAAQAAAAEAAAP+AAAAA' +
  'QAAAAUAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAAAAQAAAAABgABAAAMAAAEBAQEAAAAAAYAAAAAAAEAAAP/AAAAAAgAAAUAAgAHA' +
  'AAMABwAAAQEBAQEBAQEAQAAAAEAAAP+AAAAAQAAAAUAAQAAA/8AAQABAAAD/wAADAAAAAAEAAUAAAwANABEAAAEBAQEBAQEBAQEB' +
  'AQEBAQEBAQAAAAAAQAAAAAAAAACAAAD/gAAAAIAAAABAAAD/QAAAAIAAAABAAEAAAP/A/8AAQAAAAEAAAABAAAAAQAAA/wABAABA' +
  'AAD/wAACAAAAAAEAAcAAAwANAAABAQEBAQEBAQEBAQEBAQDAAAAAQAAA/wAAAABAAAAAgAAA/4AAAACAAAAAQADAAAD/QP/AAcAA' +
  'AP+AAAD/wAAA/0AAAP/AAAAABQAAAAABAAFAAAMABwALAA8AEwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAAAAAAAAQAAA' +
  '/wAAAABAAAAAgAAAAEAAAP9AAAAAgAAAAAAAQAAA/8AAQABAAAD/wAAAAMAAAP9AAIAAQAAA/8AAQABAAAD/wAAAAAIAAAAAAQAB' +
  'wAADAA0AAAEBAQEBAQEBAQEBAQEBAAAAAABAAAAAAAAAAIAAAP+AAAAAgAAAAEAAAABAAMAAAP9A/8AAQAAAAMAAAABAAAAAgAAA' +
  '/kAAAAADAAAAAAEAAUAAAwANABEAAAEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAA/0AAAABAAAAAgAAAAEAAAP9AAAAAAAAAAIAA' +
  'AAAAAEAAAP/AAEAAwAAA/8AAAABAAAD/gAAA/8AAwABAAAD/wAACAAAAAAEAAcAACwAPAAABAQEBAQEBAQEBAQEBAQEBAEAAAP/A' +
  'AAAAQAAAAEAAAABAAAD/wAAAAAAAAACAAAAAAAEAAAAAQAAAAEAAAP/AAAD/wAAA/wABgABAAAD/wAADAAD/gAEAAUAAAwAHABEA' +
  'AAEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAA/0AAAABAAAAAgAAA/4AAAACAAAD/gAAAAMAAAP+AAEAAAP/AAMAAwAAA/0D/gABA' +
  'AAAAQAAAAMAAAABAAAD+gAACAAAAAAEAAcAAAwALAAABAQEBAQEBAQEBAQEAwAAAAEAAAP8AAAAAQAAAAIAAAP+AAAAAAAEAAAD/' +
  'AAAAAcAAAP+AAAD/wAAA/wAAAgAAAAAAgAHAAAUACQAAAQEBAQEBAQEBAQBAAAD/wAAAAIAAAP/AAAAAQAAAAAABAAAAAEAAAP7A' +
  'AYAAQAAA/8AAAAADAAD/gADAAcAAAwAHAAsAAAEBAQEBAQEBAQEBAQAAAAAAgAAAAAAAAABAAAD/wAAAAEAAAP+AAEAAAP/AAEAB' +
  'gAAA/oABwABAAAD/wAAAAAUAAAAAAQABwAADAAcACwAPABcAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQDAAAAAQAAA/4AAAABA' +
  'AAD/wAAAAEAAAAAAAAAAQAAA/wAAAABAAAAAQAAA/8AAAAAAAEAAAP/AAEAAQAAA/8AAgABAAAD/wABAAEAAAP/A/wABwAAA/wAA' +
  'AP/AAAD/gAAAAAEAAAAAAIABwAAFAAABAQEBAQEAQAAA/8AAAACAAAAAAAGAAAAAQAAA/kAABAAAAAABwAFAAAMABwANABEAAAEB' +
  'AQEBAQEBAQEBAQEBAQEBAQDAAAAAQAAAAIAAAABAAAD+QAAAAMAAAP+AAAAAwAAAAIAAAAAAAQAAAP8AAAABAAAA/wAAAAFAAAD/' +
  'wAAA/wABAABAAAD/wAAAAAIAAAAAAQABQAADAAkAAAEBAQEBAQEBAQEAwAAAAEAAAP8AAAAAwAAA/4AAAAAAAQAAAP8AAAABQAAA' +
  '/8AAAP8AAAAABAAAAAABAAFAAAMABwALAA8AAAEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAIAA' +
  'AAAAAEAAAP/AAEAAwAAA/0AAAADAAAD/QADAAEAAAP/AAAIAAP+AAQABQAADAA0AAAEBAQEBAQEBAQEBAQEBAMAAAABAAAD/AAAA' +
  'AMAAAP+AAAAAgAAA/4AAAABAAMAAAP9A/0ABwAAA/8AAAP9AAAD/wAAA/4AAAAACAAD/gAEAAUAAAwANAAABAQEBAQEBAQEBAQEB' +
  'AQAAAAAAQAAAAIAAAP+AAAAAgAAA/4AAAADAAAAAQADAAAD/QP9AAIAAAABAAAAAwAAAAEAAAP5AAAAAAgAAAAABAAFAAAcACwAA' +
  'AQEBAQEBAQEBAQEBAAAAAABAAAAAQAAA/8AAAABAAAAAgAAAAAABQAAA/8AAAP/AAAD/QAEAAEAAAP/AAAUAAAAAAQABQAADAAcA' +
  'CwAPABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAADAAAAAAAAAAEAAAP9AAAAAgAAA/0AAAABAAAAAAAAAAMAAAAAAAEAAAP/A' +
  'AEAAQAAA/8AAQABAAAD/wABAAEAAAP/AAEAAQAAA/8AAAAACAAAAAADAAYAAAwAPAAABAQEBAQEBAQEBAQEBAQEBAIAAAABAAAD/' +
  'gAAA/8AAAABAAAAAQAAAAEAAAP/AAAAAAABAAAD/wABAAMAAAABAAAAAQAAA/8AAAP/AAAD/QAACAAAAAAEAAUAAAwAJAAABAQEB' +
  'AQEBAQEBAAAAAABAAAAAAAAAAIAAAABAAAAAQAEAAAD/AP/AAEAAAAEAAAD+wAAAAAUAAAAAAUABQAADAAcACwAPABMAAAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAIAAAABAAAD/gAAAAEAAAABAAAAAQAAA/wAAAABAAAAAwAAAAEAAAAAAAIAAAP+AAIAAgAAA/4AAAACA' +
  'AAD/gACAAEAAAP/AAAAAQAAA/8AAAAAHAAAAAAHAAUAAAwAHAAsADwATABcAGwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQCAAAAAQAAAAEAAAABAAAD/AAAAAEAAAABAAAAAQAAAAEAAAABAAAD+gAAAAEAAAAFAAAAAQAAAAAAAgAAA/4AAAACAAAD/gACA' +
  'AIAAAP+AAAAAgAAA/4AAAACAAAD/gACAAEAAAP/AAAAAQAAA/8AAAAAJAAAAAAFAAUAAAwAHAAsADwATABcAGwAfACMAAAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAQAAAAMAAAABAAAD/AAAAAEAAAABAAAAAQAAA/4AAAABAAAD/gAAA' +
  'AEAAAABAAAAAQAAA/wAAAABAAAAAwAAAAEAAAAAAAEAAAP/AAAAAQAAA/8AAQABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAQABAAAD/' +
  'wAAAAEAAAP/AAEAAQAAA/8AAAABAAAD/wAAAAAMAAP+AAQABQAADAAcADwAAAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAA/0AAAABA' +
  'AAAAgAAA/4AAAACAAAAAQAAA/4AAQAAA/8AAwAEAAAD/AP+AAEAAAABAAAABAAAA/oAAAAADAAAAAAEAAUAABQAJABEAAAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQAAAAAAQAAAAMAAAP9AAAAAQAAAAAAAAP+AAAABAAAA/8AAAAAAAIAAAP/AAAD/wACAAEAAAP/AAEAAQAAA' +
  'AEAAAP/AAAD/wAAFAAD/wADAAgAAAwAHAAsADwATAAABAQEBAQEBAQEBAQEBAQEBAQEBAQCAAAAAQAAA/4AAAABAAAD/gAAAAEAA' +
  'AAAAAAAAQAAAAAAAAABAAAD/wABAAAD/wABAAMAAAP9AAMAAQAAA/8AAQADAAAD/QADAAEAAAP/AAAAAAQAA/8AAQAIAAAMAAAEB' +
  'AQEAAAAAAEAAAP/AAkAAAP3AAAAABQAA/8AAwAIAAAMABwALAA8AEwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAEAAAAAAAAAA' +
  'QAAAAAAAAABAAAD/gAAAAEAAAP+AAAAAQAAA/8AAQAAA/8AAQADAAAD/QADAAEAAAP/AAEAAwAAA/0AAwABAAAD/wAAAAAMAAAFA' +
  'AUABwAADAAsADwAAAQEBAQEBAQEBAQEBAQEBAQAAAAAAQAAAAEAAAP/AAAAAgAAAAEAAAAAAAAAAQAAAAUAAQAAA/8AAAABAAAAA' +
  'QAAA/8AAAP/AAEAAQAAA/8AAAAACAEAAAACAAcAAAwAHAAABAQEBAQEBAQBAAAAAQAAA/8AAAABAAAAAAAFAAAD+wAGAAEAAAP/A' +
  'AAQAAAAAAUABwAADAAcACwAfAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAQAAA/sAAAABAAAAAwAAAAEAA' +
  'AP9AAAD/wAAAAEAAAP/AAAAAQAAAAEAAAABAAAD/wAAAAEAAAP/AAAAAgABAAAD/wAAAAMAAAP9AAIAAQAAA/8D/AABAAAAAQAAA' +
  'AMAAAABAAAAAQAAA/8AAAP/AAAD/QAAA/8AAAP/AAAMAAAAAAUABwAADABMAFwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAA' +
  'AABAAAD+wAAAAEAAAP/AAAAAQAAAAEAAAABAAAD/wAAAAIAAAP+AAAAAgAAAAEAAQAAA/8D/wABAAAAAgAAAAEAAAACAAAD/gAAA' +
  '/8AAAP+AAAD/wAGAAEAAAP/AAAAAAwAAAAABQAHAABcAGwAfAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQCAAAD/' +
  'gAAAAIAAAP+AAAAAQAAAAEAAAABAAAAAQAAAAEAAAP+AAAAAgAAA/4AAAP9AAAAAQAAAAMAAAABAAAAAAACAAAAAQAAAAEAAAABA' +
  'AAAAQAAA/8AAAABAAAD/wAAA/8AAAP/AAAD/wAAA/4ABgABAAAD/wAAAAEAAAP/AAAAACgAA/8ABQAIAAAMABwALAA8AEwAXABsA' +
  'HwAjACcAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAMAAAP8AAAAAQAAAAMAAAABAAAD/AAAA' +
  'AMAAAP8AAAAAQAAAAMAAAABAAAD/AAAAAMAAAP8AAAAAQAAAAMAAAABAAAD/AAAAAMAAAP/AAEAAAP/AAEAAQAAA/8AAAACAAAD/' +
  'gACAAEAAAP/AAEAAQAAA/8AAAABAAAD/wABAAEAAAP/AAEAAgAAA/4AAQABAAAD/wABAAEAAAP/AAAIAAAGAAMABwAADAAcAAAEB' +
  'AQEBAQEBAAAAAABAAAAAQAAAAEAAAAGAAEAAAP/AAAAAQAAA/8AACwAAAAACAAIAAAMABwALAA8AEwAXABsAHwAjACcAKwAAAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAgAAAAQAAAP7AAAAAQAAAAQAAAABAAAD/AAAAAIAAAP9A' +
  'AAAAQAAA/0AAAABAAAAAgAAAAIAAAACAAAAAQAAA/kAAAABAAAABAAAAAEAAAP7AAAABAAAAAAAAQAAA/8AAQABAAAD/wAAAAEAA' +
  'AP/AAEAAQAAA/8AAQACAAAD/gP/AAQAAAP8AAMAAQAAA/8D/QAEAAAD/AAEAAEAAAP/AAAAAQAAA/8AAQABAAAD/wAAAAAMAAABA' +
  'AQABwAADAAcADwAAAQEBAQEBAQEBAQEBAQEBAQAAAAABAAAA/wAAAABAAAAAAAAAAIAAAP+AAAAAwAAAAEAAQAAA/8AAwACAAAD/' +
  'gP/AAEAAAACAAAAAQAAA/wAAAAAKAAAAAAGAAUAAAwAHAAsADwATABcAGwAfACMAJwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQCAAAAAQAAAAIAAAABAAAD+wAAAAEAAAACAAAAAQAAA/sAAAABAAAAAgAAAAEAAAP9AAAAAQAAAAIAA' +
  'AABAAAD/QAAAAEAAAACAAAAAQAAAAAAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAAAQAAA/8AAQABAAAD/wAAAAEAAAP/AAEAAQAAA' +
  '/8AAAABAAAD/wABAAEAAAP/AAAAAQAAA/8AAAQBAAEABQAEAAAUAAAEBAQEBAQEAAAD/QAAAAQAAAABAAIAAAABAAAD/QAALAAAA' +
  'AAIAAgAAAwAHAAsADwATABcAIQAlACkALQAxAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQCAAAABAAAA/sAAAABAAAABAAAAAEAAAP+AAAAAQAAA/8AAAABAAAD+gAAAAEAAAABAAAAAwAAA/4AAAACAAAD/gAAAAQAA' +
  'AABAAAD+QAAAAEAAAAEAAAAAQAAA/sAAAAEAAAAAAABAAAD/wABAAEAAAP/AAAAAQAAA/8AAQABAAAD/wACAAEAAAP/A/4ABAAAA' +
  '/wAAAAEAAAD/wAAA/8AAAP/AAAD/wAAAAQAAAP8AAQAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAQAAAEAAQACAAADAAcACwAPAAAB' +
  'AQEBAQEBAQEBAQEBAQEBAEAAAACAAAD/QAAAAEAAAACAAAAAQAAA/0AAAACAAAABAABAAAD/wABAAIAAAP+AAAAAgAAA/4AAgABA' +
  'AAD/wAABAAAAAAFAAYAADwAAAQEBAQEBAQEBAQEBAQEBAQAAAAAAgAAA/4AAAACAAAAAQAAAAIAAAP+AAAAAgAAAAAAAQAAAAIAA' +
  'AABAAAAAgAAA/4AAAP/AAAD/gAAA/8AAAAACAEABQADAAcAAAwAHAAABAQEBAQEBAQBAAAAAQAAAAAAAAABAAAABQABAAAD/wABA' +
  'AEAAAP/AAAMAAP+AAUABgAADAAsADwAAAQEBAQEBAQEBAQEBAQEBAQEAAAAAQAAA/sAAAABAAAAAgAAA/4AAAACAAAAAQAAAAAAA' +
  'QAAA/8D/gAIAAAD+wAAA/8AAAP+AAMABQAAA/sAAAAADAAAAAAFAAcAAAwAHABUAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAA' +
  'AEAAAADAAAD/wAAA/8AAAP/AAAAAQAAA/8AAAAEAAAD/wAAA/8AAAADAAMAAAP9AAAAAwAAA/0D/QACAAAAAQAAAAMAAAABAAAD+' +
  'QAAAAIAAAP+AAAIAQP+AAMAAAAADAAcAAAEBAQEBAQEBAEAAAABAAAAAAAAAAEAAAP+AAEAAAP/AAEAAQAAA/8AABQAAAEABAAHA' +
  'AAMABwALAA8AEwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAQAAAP9AAAAAgAAA/0AAAABAAAAAgAAAAEAAAP9AAAAAgAAAAEAA' +
  'QAAA/8AAgABAAAD/wABAAIAAAP+AAAAAgAAA/4AAgABAAAD/wAAAAAoAQAAAAcABQAADAAcACwAPABMAFwAbAB8AIwAnAAABAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAABAAAAAgAAAAEAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAEAA' +
  'AACAAAAAQAAA/sAAAABAAAAAgAAAAEAAAP7AAAAAQAAAAIAAAABAAAAAAABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAAABAAAD/wABA' +
  'AEAAAP/AAAAAQAAA/8AAQABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAAABAAAD/wAAGAEAAAAFAAcAAAwAHAAsADwATABcAAAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQCAAAAAgAAAAAAAAABAAAD/AAAAAEAAAAAAAAAAQAAAAAAAAABAAAD/wAAAAEAAAAAAAEAAAP/A' +
  'AEAAQAAA/8AAAACAAAD/gACAAEAAAP/AAEAAQAAA/8AAgABAAAD/wAAEAEAAAAGAAkAADwATABcAGwAAAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQBAAAAAQAAAAEAAAABAAAAAQAAAAEAAAP/AAAD/QAAAAEAAAABAAAAAAAAAAEAAAP+AAAAAQAAAAAAAwAAA' +
  'AIAAAP+AAAAAgAAA/4AAAP9AAAAAgAAA/4ABQACAAAD/gACAAEAAAP/AAEAAQAAA/8AABABAAAABgAJAAA8AEwAXABsAAAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAEAAAABAAAAAQAAAAEAAAABAAAD/wAAA/0AAAABAAAAAQAAA/4AAAABAAAAAQAAA' +
  'AEAAAAAAAMAAAACAAAD/gAAAAIAAAP+AAAD/QAAAAIAAAP+AAUAAgAAA/4AAwABAAAD/wAAAAEAAAP/AAAUAQAAAAYACgAAPABcA' +
  'GwAfACMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAQAAAAEAAAABAAAAAQAAAAEAAAP/AAAD/QAAA' +
  'AEAAAP/AAAAAwAAA/8AAAP9AAAAAQAAAAMAAAABAAAD/AAAAAMAAAAAAAMAAAACAAAD/gAAAAIAAAP+AAAD/QAAAAIAAAP+AAUAA' +
  'gAAAAEAAAP/AAAD/gADAAEAAAP/AAAAAQAAA/8AAQABAAAD/wAAAAAIAAAAAAgABwAADABsAAAEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEAAAAAAEAAAADAAAD/gAAA/8AAAABAAAAAQAAAAEAAAP/AAAABQAAA/0AAAACAAAD/gAAAAMAAAAAAAIAAAP+AAAAA' +
  'wAAA/8AAAACAAAAAgAAA/4AAAACAAAAAQAAA/8AAAP+AAAD/wAAA/4AAAP/AAAYAAP+AAUABwAADAAsADwATABcAGwAAAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAQAAAAAAAAP/AAAAAwAAA/8AAAABAAAAAQAAA/sAAAABAAAAAwAAAAEAAAP8AAAAA' +
  'wAAA/4AAQAAA/8AAQABAAAAAQAAA/8AAAP/AAIAAQAAA/8AAAAFAAAD+wAEAAEAAAP/AAEAAQAAA/8AAAwAAAAABAAKAAAsADwAT' +
  'AAABAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAABAAAA/0AAAACAAAD/gAAAAMAAAP9AAAAAQAAAAAAAAABAAAAAAAHAAAD/wAAA/4AA' +
  'AP/AAAD/gAAA/8ACAABAAAD/wABAAEAAAP/AAAAABgAAAAABQAKAAAMACQARABUAHQAhAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAIAAAABAAAD/QAAAAIAAAP/AAAAAwAAA/8AAAABAAAAAQAAA/sAAAABAAAAAQAAA/8AAAACAAAAAQAAAAAAA' +
  'AABAAAAAwACAAAD/gP9AAcAAAP+AAAD+wAAAAEAAAACAAAABAAAA/kACAABAAAD/wAAAAEAAAABAAAD/wAAA/8AAQABAAAD/wAAA' +
  'AAYAAAAAAUACQAADAAcACwAPABMAFwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAADAAAD/AAAAAEAAAADAAAAAQAAA/wAA' +
  'AADAAAD/QAAAAEAAAABAAAAAQAAAAAAAQAAA/8AAQAFAAAD+wAAAAUAAAP7AAUAAQAAA/8AAgABAAAD/wAAAAEAAAP/AAAcAAAAA' +
  'AcABwAADAAcACwATABsAHwAjAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAEAAAABAAAAAwAAA/4AA' +
  'AABAAAD/QAAAAEAAAABAAAD/wAAAAMAAAP/AAAAAQAAAAEAAAP8AAAAAwAAAAEAAAABAAAAAAABAAAD/wAAAAEAAAP/AAMAAQAAA' +
  '/8D/gAFAAAD/QAAA/8AAAP/AAAAAwAAAAEAAAABAAAD+wAFAAEAAAP/AAAAAQAAA/8AAAAAFAAAAAAFAAkAAAwAHAAsADwATAAAB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAwAAA/wAAAABAAAAAwAAAAEAAAP8AAAAAQAAAAEAAAABAAAAAAABAAAD/wABAAYAAAP6A' +
  'AAABgAAA/oABwABAAAD/wAAAAEAAAP/AAAAABgAAAAABQAHAAAMABwALAA8AEwAXAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEA' +
  'gAAAAIAAAAAAAAAAQAAA/0AAAACAAAD/AAAAAEAAAADAAAAAQAAA/wAAAADAAAAAAABAAAD/wABAAIAAAP+AAIAAQAAA/8D/QAGA' +
  'AAD+gAEAAIAAAP+AAIAAQAAA/8AABAAAAAABAAIAAAMACwAPABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAABAAAAAAAAAAIAA' +
  'AP+AAAAAwAAA/4AAAABAAAD/gAAAAEAAAABAAMAAAP9A/8AAQAAAAMAAAABAAAD+wAGAAEAAAP/AAEAAQAAA/8AABAAAAAABAAIA' +
  'AAMACwAPABMAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAABAAAAAAAAAAIAAAP+AAAAAwAAA/0AAAABAAAAAAAAAAEAAAABAAMAA' +
  'AP9A/8AAQAAAAMAAAABAAAD+wAGAAEAAAP/AAEAAQAAA/8AABQAAAAABAAIAAAMACwAPABMAFwAAAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAAAAAABAAAAAAAAAAIAAAP+AAAAAwAAA/0AAAABAAAAAQAAAAEAAAP+AAAAAQAAAAEAAwAAA/0D/wABAAAAAwAAAAEAA' +
  'AP7AAYAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAAABgAAAAABAAIAAAMACwAPABMAFwAbAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAAAAAABAAAAAAAAAAIAAAP+AAAAAwAAA/wAAAABAAAAAQAAAAEAAAP+AAAAAQAAAAEAAAABAAAAAQADAAAD/QP/AAEAA' +
  'AADAAAAAQAAA/sABgABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAAABAAAD/wAAEAAAAAAEAAcAAAwALAA8AEwAAAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEAAAAAAEAAAAAAAAAAgAAA/4AAAADAAAD/QAAAAEAAAABAAAAAQAAAAEAAwAAA/0D/wABAAAAAwAAAAEAAAP7AAYAA' +
  'QAAA/8AAAABAAAD/wAAGAAAAAAEAAkAAAwALAA8AEwAXABsAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAEAAAAAA' +
  'AAAAgAAA/4AAAADAAAD/QAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAIAAAABAAMAAAP9A/8AAQAAAAMAAAABAAAD+wAGAAEAA' +
  'AP/AAEAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAIAQAAAAgABQAADABUAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAEAAAAAA' +
  'AAAAgAAA/4AAAAFAAAD/gAAAAIAAAABAAAD/QAAAAIAAAABAAMAAAP9A/8AAQAAAAMAAAABAAAD/wAAA/8AAAABAAAD/gAAA/8AA' +
  'AP/AAAAABgAA/4ABAAFAAAMACQANABEAFQAZAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAQAAAAAAAAP/AAAAAgAAA' +
  'AAAAAABAAAD/AAAAAEAAAACAAAAAQAAA/0AAAACAAAD/gABAAAD/wABAAEAAAABAAAD/gACAAEAAAP/AAAAAwAAA/0AAgABAAAD/' +
  'wABAAEAAAP/AAAAABQAAAAABAAIAAAMADQARABUAGQAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAA' +
  'AIAAAABAAAD/QAAAAAAAAACAAAD/wAAAAEAAAP+AAAAAQAAAAAAAQAAA/8AAQADAAAD/wAAAAEAAAP+AAAD/wADAAEAAAP/AAIAA' +
  'QAAA/8AAQABAAAD/wAAFAAAAAAEAAgAAAwANABEAFQAZAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAA/0AAAABA' +
  'AAAAgAAAAEAAAP9AAAAAAAAAAIAAAP+AAAAAQAAAAAAAAABAAAAAAABAAAD/wABAAMAAAP/AAAAAQAAA/4AAAP/AAMAAQAAA/8AA' +
  'gABAAAD/wABAAEAAAP/AAAYAAAAAAQACAAADAA0AEQAVABkAHQAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEAAAACA' +
  'AAD/QAAAAEAAAACAAAAAQAAA/0AAAAAAAAAAgAAA/0AAAABAAAAAQAAAAEAAAP+AAAAAQAAAAAAAQAAA/8AAQADAAAD/wAAAAEAA' +
  'AP+AAAD/wADAAEAAAP/AAIAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAAABQAAAAABAAHAAAMADQARABUAGQAAAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAAAAAACAAAD/QAAAAEAAAACAAAAAQAAAAAAAQAAA/8AA' +
  'QADAAAD/wAAAAEAAAP+AAAD/wADAAEAAAP/AAIAAQAAA/8AAAABAAAD/wAADAAAAAACAAgAABQAJAA0AAAEBAQEBAQEBAQEBAQEB' +
  'AEAAAP/AAAAAgAAA/8AAAABAAAD/gAAAAEAAAAAAAQAAAABAAAD+wAGAAEAAAP/AAEAAQAAA/8AAAwAAAAAAgAIAAAUACQANAAAB' +
  'AQEBAQEBAQEBAQEBAQBAAAD/wAAAAIAAAP+AAAAAQAAAAAAAAABAAAAAAAEAAAAAQAAA/sABgABAAAD/wABAAEAAAP/AAAQAAAAA' +
  'AMACAAAFAAkADQARAAABAQEBAQEBAQEBAQEBAQEBAQEAQAAA/8AAAACAAAD/gAAAAEAAAABAAAAAQAAA/4AAAABAAAAAAAEAAAAA' +
  'QAAA/sABgABAAAD/wAAAAEAAAP/AAEAAQAAA/8AAAAADAAAAAADAAcAABQAJAA0AAAEBAQEBAQEBAQEBAQEBAEAAAP/AAAAAgAAA' +
  '/4AAAABAAAAAQAAAAEAAAAAAAQAAAABAAAD+wAGAAEAAAP/AAAAAQAAA/8AABgAAAAABAAIAAAMACQANABEAFQAZAAABAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQDAAAAAQAAA/wAAAADAAAD/gAAA/8AAAABAAAAAQAAAAEAAAP+AAAAAQAAAAEAAAABAAAAAAAEA' +
  'AAD/AAAAAUAAAP/AAAD/AAGAAEAAAP/AAAAAQAAA/8AAQABAAAD/wAAAAEAAAP/AAAAABgAAAAABAAIAAAMABwALAA8AEwAXAAAB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAIAAAP/AAAAAQAAA/4AAAABAAAAAAABA' +
  'AAD/wABAAMAAAP9AAAAAwAAA/0AAwABAAAD/wACAAEAAAP/AAEAAQAAA/8AABgAAAAABAAIAAAMABwALAA8AEwAXAAABAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAIAAAP+AAAAAQAAAAAAAAABAAAAAAABAAAD/wABA' +
  'AMAAAP9AAAAAwAAA/0AAwABAAAD/wACAAEAAAP/AAEAAQAAA/8AABwAAAAABAAIAAAMABwALAA8AEwAXABsAAAEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAIAAAP9AAAAAQAAAAEAAAABAAAD/gAAAAEAAAAAA' +
  'AEAAAP/AAEAAwAAA/0AAAADAAAD/QADAAEAAAP/AAIAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAAACAAAAAABAAIAAAMABwALAA8A' +
  'EwAXABsAHwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAIAAAP9AAAAAQAAAAIAAAABAAAD/QAAAAIAAAP9A' +
  'AAAAQAAAAEAAAABAAAD/gAAAAEAAAABAAAAAQAAAAAAAQAAA/8AAQADAAAD/QAAAAMAAAP9AAMAAQAAA/8AAgABAAAD/wAAAAEAA' +
  'AP/AAEAAQAAA/8AAAABAAAD/wAAGAAAAAAEAAcAAAwAHAAsADwATABcAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAAAAAgAAA' +
  '/0AAAABAAAAAgAAAAEAAAP9AAAAAgAAA/0AAAABAAAAAgAAAAEAAAAAAAEAAAP/AAEAAwAAA/0AAAADAAAD/QADAAEAAAP/AAIAA' +
  'QAAA/8AAAABAAAD/wAADAAAAQAFAAYAAAwAHAAsAAAEBAQEBAQEBAQEBAQCAAAAAQAAA/0AAAAFAAAD/QAAAAEAAAABAAEAAAP/A' +
  'AIAAQAAA/8AAgABAAAD/wAAAAAYAAAAAAYABgAADAAcADwAXABsAHwAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEA' +
  'AAAAAEAAAABAAAAAgAAA/0AAAABAAAAAQAAA/8AAAACAAAD/wAAAAEAAAABAAAD/QAAAAIAAAABAAAAAQAAAAAAAQAAA/8AAAABA' +
  'AAD/wABAAQAAAP+AAAD/wAAA/8AAAACAAAAAQAAAAEAAAP8AAQAAQAAA/8AAAABAAAD/wAAEAAAAAAEAAgAAAwAJAA0AEQAAAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAAAAAABAAAAAAAAAAIAAAABAAAD/gAAAAEAAAP+AAAAAQAAAAEABAAAA/wD/wABAAAABAAAA/sABgABA' +
  'AAD/wABAAEAAAP/AAAAABAAAAAABAAIAAAMACQANABEAAAEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAQAAAAAAAAACAAAAAQAAA/0AA' +
  'AABAAAAAAAAAAEAAAABAAQAAAP8A/8AAQAAAAQAAAP7AAYAAQAAA/8AAQABAAAD/wAAAAAUAAAAAAQACAAADAAkADQARABUAAAEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAEAAAAAAAAAAgAAAAEAAAP8AAAAAQAAAAEAAAABAAAD/gAAAAEAAAABAAQAAAP8A/8AA' +
  'QAAAAQAAAP7AAYAAQAAA/8AAAABAAAD/wABAAEAAAP/AAAQAAAAAAQABwAADAAkADQARAAABAQEBAQEBAQEBAQEBAQEBAQEAAAAA' +
  'AEAAAAAAAAAAgAAAAEAAAP8AAAAAQAAAAIAAAABAAAAAQAEAAAD/AP/AAEAAAAEAAAD+wAGAAEAAAP/AAAAAQAAA/8AAAAAFAAD/' +
  'gAFAAcAAAwAHAA8AEwAXAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQAAAAMAAAP8AAAAAQAAAAMAAAP9AAAAAwAAAAEAAAP7A' +
  'AAAAQAAAAIAAAABAAAD/gABAAAD/wADAAQAAAP8A/4AAQAAAAEAAAAEAAAD+gAHAAEAAAP/AAAAAQAAA/8AAAAADAAAAAAFAAcAA' +
  'AwAHAAsAAAEBAQEBAQEBAQEBAQBAAAAAwAAA/wAAAABAAAAAwAAAAEAAAAAAAEAAAP/AAEABgAAA/oAAAAGAAAD+gAAAAAIAAAAA' +
  'AQABQAADAAkAAAEBAQEBAQEBAQEAAAAAAEAAAAAAAAAAgAAAAEAAAABAAQAAAP8A/8AAQAAAAQAAAP7AAAAAAQAAAIABgADAAAMA' +
  'AAEBAQEAAAAAAYAAAACAAEAAAP/AAAAAAgBAAUAAwAIAAAMABwAAAQEBAQEBAQEAQAAAAEAAAAAAAAAAQAAAAUAAgAAA/4AAgABA' +
  'AAD/wAACAEABQADAAgAAAwAHAAABAQEBAQEBAQBAAAAAQAAAAAAAAABAAAABQABAAAD/wABAAIAAAP+AAAQAQAFAAUACAAADAAcA' +
  'CwAPAAABAQEBAQEBAQEBAQEBAQEBAEAAAABAAAAAQAAAAEAAAP+AAAAAQAAAAEAAAABAAAABQACAAAD/gAAAAIAAAP+AAIAAQAAA' +
  '/8AAAABAAAD/wAAEAIABQAGAAgAAAwAHAAsADwAAAQEBAQEBAQEBAQEBAQEBAQCAAAAAQAAAAEAAAABAAAD/gAAAAEAAAABAAAAA' +
  'QAAAAUAAQAAA/8AAAABAAAD/wABAAIAAAP+AAAAAgAAA/4AAAQAAAMAAwAIAAAsAAAEBAQEBAQEBAQEBAQBAAAD/wAAAAEAAAABA' +
  'AAAAQAAA/8AAAADAAMAAAABAAAAAQAAA/8AAAP/AAAD/QAAAAAEAAABAAUABgAALAAABAQEBAQEBAQEBAQEAQAAA/8AAAABAAAAA' +
  'wAAAAEAAAP/AAAAAQABAAAAAwAAAAEAAAP/AAAD/QAAA/8AAAAADAAAAAAHAAEAAAwAHAAsAAAEBAQEBAQEBAQEBAQAAAAAAQAAA' +
  'AIAAAABAAAAAgAAAAEAAAAAAAEAAAP/AAAAAQAAA/8AAAABAAAD/wAAAAAMAAADAAgABwAADABEAGQAAAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBQAAAAEAAAP7AAAD/wAAAAQAAAABAAAD/wAAA/8AAAP/AAAABQAAA/8AAAABAAAAAQAAAAQAAQAAA/8D/wADA' +
  'AAAAQAAA/8AAAP/AAAD/gAAAAMAAAP9AAAAAgAAAAEAAAABAAAD/AAAAADMCagAAAAAAAAAAADgAAAAAAAAAAAABABAAOAAAAAAA' +
  'AAACAA4ASAAAAAAAAAADABAAVgAAAAAAAAAEACAAZgAAAAAAAAAFABYAhgAAAAAAAAAGAA4AnAAAAAAAAAAHAFYAqgAAAAAAAAAI' +
  'ACwBAAAAAAAAAAAJABoBLAAAAAAAAAAKBpQBRgAAAAAAAAALAHQH2gAAAAAAAAAMAHwITgAAAAAAAAANADgIygAAAAAAAAAOAFYJ' +
  'AgAAAAAAAAATAFIJWAAAAAAAAAEAABAJqgABAAAAAAAAABwJugABAAAAAAABAAgJ1gABAAAAAAACAAcJ3gABAAAAAAADAAgJ5QAB' +
  'AAAAAAAEABAJ7QABAAAAAAAFAAsJ/QABAAAAAAAGAAcKCAABAAAAAAAHACsKDwABAAAAAAAIABYKOgABAAAAAAAJAA0KUAABAAAA' +
  'AAAKA0IKXQABAAAAAAALADoNnwABAAAAAAAMAD4N2QABAAAAAAANABwOFwABAAAAAAAOACsOMwABAAAAAAATACkOXgABAAAAAAEA' +
  'AAgOhwADAAEECQAAADgOjwADAAEECQABABAOxwADAAEECQACAA4O1wADAAEECQADABAO5QADAAEECQAEACAO9QADAAEECQAFABYP' +
  'FQADAAEECQAGAA4PKwADAAEECQAHAFYPOQADAAEECQAIACwPjwADAAEECQAJABoPuwADAAEECQAKBpQP1QADAAEECQALAHQWaQAD' +
  'AAEECQAMAHwW3QADAAEECQANADgXWQADAAEECQAOAFYXkQADAAEECQATAFIX5wADAAEECQEAABAYOQBDAG8AcAB5AHIAaQBnAGgA' +
  'dAAgAEsAZQBsAHMAZQB5ACAASABpAGcAaABhAG0AIAAyADAAMQAwAEcAZQBuAGUAdgBhACAAOQBSAGUAZwB1AGwAYQByAEcAZQBu' +
  'AGUAdgBhACAAOQBHAGUAbgBlAHYAYQAgADkAIABSAGUAZwB1AGwAYQByAFYAZQByAHMAaQBvAG4AIAAxAC4AMABHAGUAbgBlAHYA' +
  'YQA5AEYAbwBuAHQAUwB0AHIAdQBjAHQAIABpAHMAIABhACAAdAByAGEAZABlAG0AYQByAGsAIABvAGYAIABGAG8AbgB0AFMAdABy' +
  'AHUAYwB0AC4AYwBvAG0AaAB0AHQAcABzADoALwAvAGYAbwBuAHQAcwB0AHIAdQBjAHQALgBjAG8AbQBLAGUAbABzAGUAeQAgAEgA' +
  'aQBnAGgAYQBtIBwARwBlAG4AZQB2AGEAIAA5IB0AIAB3AGEAcwAgAGIAdQBpAGwAdAAgAHcAaQB0AGgAIABGAG8AbgB0AFMAdABy' +
  'AHUAYwB0AAoARABlAHMAaQBnAG4AZQByACAAZABlAHMAYwByAGkAcAB0AGkAbwBuADoAIAA8AHAAPgBBACAAYwBsAG8AbgBlACAA' +
  'bwBmACAARwBlAG4AZQB2AGEAIABzAGkAegBlACAAOQAsACAAdwBhAHkAIABiAGEAYwBrACAAZgByAG8AbQAgAHQAaABlACAAbwBy' +
  'AGkAZwBpAG4AYQBsACAATQBhAGMAaQBuAHQAbwBzAGgALgAgAEMAcgBlAGEAdABlAGQAIABiAHkAIAByAGUAZgBlAHIAZQBuAGMA' +
  'aQBuAGcAIABNAGEAYwBQAGEAaQBuAHQAIAAxAC4ANAAgAGkAbgAgAE0AaQBuAGkAIAB2AE0AYQBjAC4APAAvAHAAPgAKAAoAPABw' +
  'AD4AQQBzACAAZgBhAHIAIABhAHMAIABJACAAawBuAG8AdwAsACAAaQB0ACcAcwAgAGMAbwBtAHAAbABlAHQAZQAgAGEAbgBkACYA' +
  'bgBiAHMAcAA7AGEAYwBjAHUAcgBhAHQAZQAgAHQAbwAgAHQAaABlACAAZgBpAHIAcwB0ACAAdgBlAHIAcwBpAG8AbgAgAG8AZgAg' +
  'AHQAaABlACAAZgBvAG4AdAAuACAATQBvAHMAdAAgAGMAaABhAHIAYQBjAHQAZQByAHMAIABoAGEAdgBlACAAYQAgAG8AbgBlAC0A' +
  'cABpAHgAZQBsACAAcwBwAGEAYwBlACAAaQBtAG0AZQBkAGkAYQB0AGUAbAB5ACAAYQBmAHQAZQByACAAdABoAGUAbQAsACAAYQBu' +
  'AGQAIABuAG8AIABzAHAAYQBjAGUAIABiAGUAZgBvAHIAZQAgAHQAaABlAG0ALAAgAHcAaQB0AGgAIAB0AGgAZQAgAHIAZQBzAHUA' +
  'bAB0ACAAdABoAGEAdAAgAGcAZQBuAGUAcgBhAGwAbAB5ACwAIAB0AGgAZQByAGUAIABpAHMAIABhACAAbwBuAGUALQBwAGkAeABl' +
  'AGwAIABzAHAAYQBjAGUAIABiAGUAdAB3AGUAZQBuACAAZQBhAGMAaAAgAHAAYQBpAHIAIABvAGYAIABjAGgAYQByAGEAYwB0AGUA' +
  'cgBzAC4AIABTAG8AbQBlACAAYwBoAGEAcgBhAGMAdABlAHIAcwAsACAAbABpAGsAZQAgACIAQQAiACAAYQBuAGQAIAAiAKsAIgAs' +
  'ACAAZABlAGYAeQAgAHQAaABpAHMAIABjAG8AbgB2AGUAbgB0AGkAbwBuADsAIABJACcAdgBlACAAbQBhAGQAZQAgAHQAaABlAG0A' +
  'IABtAGEAdABjAGgAIAB0AGgAZQAgAG8AcgBpAGcAaQBuAGEAbAAgAGYAbwBuAHQALAAgAGUAdgBlAG4AIABpAG4AIABjAGEAcwBl' +
  'AHMAIAAoAGwAaQBrAGUAIAAiAEEAIgApACAAdwBoAGUAcgBlACAASQAgAGQAaQBkAG4AJwB0ACAAcwBlAGUAIAB3AGgAeQAgAHQA' +
  'aABlACAAZABlAHYAaQBhAHQAaQBvAG4AIAB3AGEAcwAgAG4AZQBjAGUAcwBzAGEAcgB5AC4AJgBuAGIAcwBwADsAPAAvAHAAPgAK' +
  'AAoAPABwAD4AQQAgAHYAZQByAHMAaQBvAG4AIAB3AGkAdABoACAAbQBvAHIAZQAgAGEAYwBjAGUAbgB0AGUAZAAgAGMAaABhAHIA' +
  'YQBjAHQAZQByAHMALAAgAG0AbwBkAGUAcgBuAGkAegBlAGQAIABwAHUAbgBjAHQAdQBhAHQAaQBvAG4AIAAoAHMAdQBjAGgAIABh' +
  'AHMAIABsAGEAcgBnAGUAcgAgACMAIABhAG4AZAAgAGwAbwB3AGUAcgBlAGQAIAAvAFwAKQAsACAAYQBuAGQAIAB0AGkAZwBoAHQA' +
  'ZQByACAAcwBwAGEAYwBpAG4AZwAgAGkAcwAgAGgAZQByAGUAOgAmAG4AYgBzAHAAOwBoAHQAdABwADoALwAvAGYAbwBuAHQAcwB0' +
  'AHIAdQBjAHQALgBjAG8AbQAvAGYAbwBuAHQAcwB0AHIAdQBjAHQAaQBvAG4AcwAvAHMAaABvAHcALwAxADMAMAA0ADcANwA1AC8A' +
  'ZwBlAG4AZQB2AGEALQA5ADwALwBwAD4ACgAKADwAcAA+ADwALwBwAD4ACgBoAHQAdABwAHMAOgAvAC8AZgBvAG4AdABzAHQAcgB1' +
  'AGMAdAAuAGMAbwBtAC8AZgBvAG4AdABzAHQAcgB1AGMAdABpAG8AbgBzAC8AcwBoAG8AdwAvADMANAA5ADIANwA3AC8AZwBlAG4A' +
  'ZQB2AGEAXwA5AGgAdAB0AHAAcwA6AC8ALwBmAG8AbgB0AHMAdAByAHUAYwB0AC4AYwBvAG0ALwBmAG8AbgB0AHMAdAByAHUAYwB0' +
  'AG8AcgBzAC8AcwBoAG8AdwAvADIAOQAxADEAMQAzAC8AawBlAGwAcwBlAHkAXwBoAGkAZwBoAGEAbQBDAHIAZQBhAHQAaQB2AGUA' +
  'IABDAG8AbQBtAG8AbgBzACAAQQB0AHQAcgBpAGIAdQB0AGkAbwBuAGgAdAB0AHAAOgAvAC8AYwByAGUAYQB0AGkAdgBlAGMAbwBt' +
  'AG0AbwBuAHMALgBvAHIAZwAvAGwAaQBjAGUAbgBzAGUAcwAvAGIAeQAvADMALgAwAC8ARgBpAHYAZQAgAGIAaQBnACAAcQB1AGEA' +
  'YwBrAGkAbgBnACAAegBlAHAAaAB5AHIAcwAgAGoAbwBsAHQAIABtAHkAIAB3AGEAeAAgAGIAZQBkAEEAUQAwAEIAZAAxADUAakNv' +
  'cHlyaWdodCBLZWxzZXkgSGlnaGFtIDIwMTBHZW5ldmEgOVJlZ3VsYXJHZW5ldmEgOUdlbmV2YSA5IFJlZ3VsYXJWZXJzaW9uIDEu' +
  'MEdlbmV2YTlGb250U3RydWN0IGlzIGEgdHJhZGVtYXJrIG9mIEZvbnRTdHJ1Y3QuY29taHR0cHM6Ly9mb250c3RydWN0LmNvbUtl' +
  'bHNleSBIaWdoYW3SR2VuZXZhIDnTIHdhcyBidWlsdCB3aXRoIEZvbnRTdHJ1Y3REZXNpZ25lciBkZXNjcmlwdGlvbjogPHA+QSBj' +
  'bG9uZSBvZiBHZW5ldmEgc2l6ZSA5LCB3YXkgYmFjayBmcm9tIHRoZSBvcmlnaW5hbCBNYWNpbnRvc2guIENyZWF0ZWQgYnkgcmVm' +
  'ZXJlbmNpbmcgTWFjUGFpbnQgMS40IGluIE1pbmkgdk1hYy48L3A+PHA+QXMgZmFyIGFzIEkga25vdywgaXQncyBjb21wbGV0ZSBh' +
  'bmQmbmJzcDthY2N1cmF0ZSB0byB0aGUgZmlyc3QgdmVyc2lvbiBvZiB0aGUgZm9udC4gTW9zdCBjaGFyYWN0ZXJzIGhhdmUgYSBv' +
  'bmUtcGl4ZWwgc3BhY2UgaW1tZWRpYXRlbHkgYWZ0ZXIgdGhlbSwgYW5kIG5vIHNwYWNlIGJlZm9yZSB0aGVtLCB3aXRoIHRoZSBy' +
  'ZXN1bHQgdGhhdCBnZW5lcmFsbHksIHRoZXJlIGlzIGEgb25lLXBpeGVsIHNwYWNlIGJldHdlZW4gZWFjaCBwYWlyIG9mIGNoYXJh' +
  'Y3RlcnMuIFNvbWUgY2hhcmFjdGVycywgbGlrZSAiQSIgYW5kICLHIiwgZGVmeSB0aGlzIGNvbnZlbnRpb247IEkndmUgbWFkZSB0' +
  'aGVtIG1hdGNoIHRoZSBvcmlnaW5hbCBmb250LCBldmVuIGluIGNhc2VzIChsaWtlICJBIikgd2hlcmUgSSBkaWRuJ3Qgc2VlIHdo' +
  'eSB0aGUgZGV2aWF0aW9uIHdhcyBuZWNlc3NhcnkuJm5ic3A7PC9wPjxwPkEgdmVyc2lvbiB3aXRoIG1vcmUgYWNjZW50ZWQgY2hh' +
  'cmFjdGVycywgbW9kZXJuaXplZCBwdW5jdHVhdGlvbiAoc3VjaCBhcyBsYXJnZXIgIyBhbmQgbG93ZXJlZCAvXCksIGFuZCB0aWdo' +
  'dGVyIHNwYWNpbmcgaXMgaGVyZTombmJzcDtodHRwOi8vZm9udHN0cnVjdC5jb20vZm9udHN0cnVjdGlvbnMvc2hvdy8xMzA0Nzc1' +
  'L2dlbmV2YS05PC9wPjxwPjwvcD5odHRwczovL2ZvbnRzdHJ1Y3QuY29tL2ZvbnRzdHJ1Y3Rpb25zL3Nob3cvMzQ5Mjc3L2dlbmV2' +
  'YV85aHR0cHM6Ly9mb250c3RydWN0LmNvbS9mb250c3RydWN0b3JzL3Nob3cvMjkxMTEzL2tlbHNleV9oaWdoYW1DcmVhdGl2ZSBD' +
  'b21tb25zIEF0dHJpYnV0aW9uaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvYnkvMy4wL0ZpdmUgYmlnIHF1YWNr' +
  'aW5nIHplcGh5cnMgam9sdCBteSB3YXggYmVkQVEwQmQxNWoAQwBvAHAAeQByAGkAZwBoAHQAIABLAGUAbABzAGUAeQAgAEgAaQBn' +
  'AGgAYQBtACAAMgAwADEAMABHAGUAbgBlAHYAYQAgADkAUgBlAGcAdQBsAGEAcgBHAGUAbgBlAHYAYQAgADkARwBlAG4AZQB2AGEA' +
  'IAA5ACAAUgBlAGcAdQBsAGEAcgBWAGUAcgBzAGkAbwBuACAAMQAuADAARwBlAG4AZQB2AGEAOQBGAG8AbgB0AFMAdAByAHUAYwB0' +
  'ACAAaQBzACAAYQAgAHQAcgBhAGQAZQBtAGEAcgBrACAAbwBmACAARgBvAG4AdABTAHQAcgB1AGMAdAAuAGMAbwBtAGgAdAB0AHAA' +
  'cwA6AC8ALwBmAG8AbgB0AHMAdAByAHUAYwB0AC4AYwBvAG0ASwBlAGwAcwBlAHkAIABIAGkAZwBoAGEAbSAcAEcAZQBuAGUAdgBh' +
  'ACAAOSAdACAAdwBhAHMAIABiAHUAaQBsAHQAIAB3AGkAdABoACAARgBvAG4AdABTAHQAcgB1AGMAdAAKAEQAZQBzAGkAZwBuAGUA' +
  'cgAgAGQAZQBzAGMAcgBpAHAAdABpAG8AbgA6ACAAPABwAD4AQQAgAGMAbABvAG4AZQAgAG8AZgAgAEcAZQBuAGUAdgBhACAAcwBp' +
  'AHoAZQAgADkALAAgAHcAYQB5ACAAYgBhAGMAawAgAGYAcgBvAG0AIAB0AGgAZQAgAG8AcgBpAGcAaQBuAGEAbAAgAE0AYQBjAGkA' +
  'bgB0AG8AcwBoAC4AIABDAHIAZQBhAHQAZQBkACAAYgB5ACAAcgBlAGYAZQByAGUAbgBjAGkAbgBnACAATQBhAGMAUABhAGkAbgB0' +
  'ACAAMQAuADQAIABpAG4AIABNAGkAbgBpACAAdgBNAGEAYwAuADwALwBwAD4ACgAKADwAcAA+AEEAcwAgAGYAYQByACAAYQBzACAA' +
  'SQAgAGsAbgBvAHcALAAgAGkAdAAnAHMAIABjAG8AbQBwAGwAZQB0AGUAIABhAG4AZAAmAG4AYgBzAHAAOwBhAGMAYwB1AHIAYQB0' +
  'AGUAIAB0AG8AIAB0AGgAZQAgAGYAaQByAHMAdAAgAHYAZQByAHMAaQBvAG4AIABvAGYAIAB0AGgAZQAgAGYAbwBuAHQALgAgAE0A' +
  'bwBzAHQAIABjAGgAYQByAGEAYwB0AGUAcgBzACAAaABhAHYAZQAgAGEAIABvAG4AZQAtAHAAaQB4AGUAbAAgAHMAcABhAGMAZQAg' +
  'AGkAbQBtAGUAZABpAGEAdABlAGwAeQAgAGEAZgB0AGUAcgAgAHQAaABlAG0ALAAgAGEAbgBkACAAbgBvACAAcwBwAGEAYwBlACAA' +
  'YgBlAGYAbwByAGUAIAB0AGgAZQBtACwAIAB3AGkAdABoACAAdABoAGUAIAByAGUAcwB1AGwAdAAgAHQAaABhAHQAIABnAGUAbgBl' +
  'AHIAYQBsAGwAeQAsACAAdABoAGUAcgBlACAAaQBzACAAYQAgAG8AbgBlAC0AcABpAHgAZQBsACAAcwBwAGEAYwBlACAAYgBlAHQA' +
  'dwBlAGUAbgAgAGUAYQBjAGgAIABwAGEAaQByACAAbwBmACAAYwBoAGEAcgBhAGMAdABlAHIAcwAuACAAUwBvAG0AZQAgAGMAaABh' +
  'AHIAYQBjAHQAZQByAHMALAAgAGwAaQBrAGUAIAAiAEEAIgAgAGEAbgBkACAAIgCrACIALAAgAGQAZQBmAHkAIAB0AGgAaQBzACAA' +
  'YwBvAG4AdgBlAG4AdABpAG8AbgA7ACAASQAnAHYAZQAgAG0AYQBkAGUAIAB0AGgAZQBtACAAbQBhAHQAYwBoACAAdABoAGUAIABv' +
  'AHIAaQBnAGkAbgBhAGwAIABmAG8AbgB0ACwAIABlAHYAZQBuACAAaQBuACAAYwBhAHMAZQBzACAAKABsAGkAawBlACAAIgBBACIA' +
  'KQAgAHcAaABlAHIAZQAgAEkAIABkAGkAZABuACcAdAAgAHMAZQBlACAAdwBoAHkAIAB0AGgAZQAgAGQAZQB2AGkAYQB0AGkAbwBu' +
  'ACAAdwBhAHMAIABuAGUAYwBlAHMAcwBhAHIAeQAuACYAbgBiAHMAcAA7ADwALwBwAD4ACgAKADwAcAA+AEEAIAB2AGUAcgBzAGkA' +
  'bwBuACAAdwBpAHQAaAAgAG0AbwByAGUAIABhAGMAYwBlAG4AdABlAGQAIABjAGgAYQByAGEAYwB0AGUAcgBzACwAIABtAG8AZABl' +
  'AHIAbgBpAHoAZQBkACAAcAB1AG4AYwB0AHUAYQB0AGkAbwBuACAAKABzAHUAYwBoACAAYQBzACAAbABhAHIAZwBlAHIAIAAjACAA' +
  'YQBuAGQAIABsAG8AdwBlAHIAZQBkACAALwBcACkALAAgAGEAbgBkACAAdABpAGcAaAB0AGUAcgAgAHMAcABhAGMAaQBuAGcAIABp' +
  'AHMAIABoAGUAcgBlADoAJgBuAGIAcwBwADsAaAB0AHQAcAA6AC8ALwBmAG8AbgB0AHMAdAByAHUAYwB0AC4AYwBvAG0ALwBmAG8A' +
  'bgB0AHMAdAByAHUAYwB0AGkAbwBuAHMALwBzAGgAbwB3AC8AMQAzADAANAA3ADcANQAvAGcAZQBuAGUAdgBhAC0AOQA8AC8AcAA+' +
  'AAoACgA8AHAAPgA8AC8AcAA+AAoAaAB0AHQAcABzADoALwAvAGYAbwBuAHQAcwB0AHIAdQBjAHQALgBjAG8AbQAvAGYAbwBuAHQA' +
  'cwB0AHIAdQBjAHQAaQBvAG4AcwAvAHMAaABvAHcALwAzADQAOQAyADcANwAvAGcAZQBuAGUAdgBhAF8AOQBoAHQAdABwAHMAOgAv' +
  'AC8AZgBvAG4AdABzAHQAcgB1AGMAdAAuAGMAbwBtAC8AZgBvAG4AdABzAHQAcgB1AGMAdABvAHIAcwAvAHMAaABvAHcALwAyADkA' +
  'MQAxADEAMwAvAGsAZQBsAHMAZQB5AF8AaABpAGcAaABhAG0AQwByAGUAYQB0AGkAdgBlACAAQwBvAG0AbQBvAG4AcwAgAEEAdAB0' +
  'AHIAaQBiAHUAdABpAG8AbgBoAHQAdABwADoALwAvAGMAcgBlAGEAdABpAHYAZQBjAG8AbQBtAG8AbgBzAC4AbwByAGcALwBsAGkA' +
  'YwBlAG4AcwBlAHMALwBiAHkALwAzAC4AMAAvAEYAaQB2AGUAIABiAGkAZwAgAHEAdQBhAGMAawBpAG4AZwAgAHoAZQBwAGgAeQBy' +
  'AHMAIABqAG8AbAB0ACAAbQB5ACAAdwBhAHgAIABiAGUAZABBAFEAMABCAGQAMQA1AGoAAAMAAAAAAAAAZgAzAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAABAAAAAA==';

const GENEVA_METRICS = {
  9: { ascent: 10, descent: 2, leading: 0,
    adv: [3, 3, 5, 7, 6, 9, 8, 3, 4, 4, 7, 6, 4, 5, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 5, 6, 5, 6, 8, 7, 6, 6, 6, 5, 5, 6, 6, 3, 6, 6, 5, 8, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 5, 4, 6, 4, 4, 6, 3, 5, 5, 5, 5, 5, 4, 5, 5, 3, 4, 5, 3, 8, 5, 5, 5, 5, 5, 5, 4, 5, 6, 8, 6, 6, 5, 4, 2, 4, 6],
    lsb: [3, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  10: { ascent: 10, descent: 2, leading: 1,
    adv: [3, 4, 5, 9, 7, 10, 8, 3, 6, 6, 7, 8, 4, 7, 3, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 4, 5, 7, 5, 7, 9, 6, 7, 6, 7, 6, 6, 6, 7, 4, 6, 7, 6, 9, 7, 6, 7, 6, 7, 6, 6, 7, 6, 10, 6, 6, 6, 5, 5, 5, 5, 7, 4, 5, 6, 5, 5, 5, 4, 5, 6, 4, 5, 6, 4, 9, 6, 5, 6, 5, 6, 5, 4, 6, 6, 8, 6, 6, 5, 5, 4, 5, 7],
    lsb: [3, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0] },
};

// The font as bytes, decoded once. Base64 by hand rather than atob, which
// the utilities' sandbox does not have.
function geneva9Bytes() {
  if (geneva9Bytes.cache) return geneva9Bytes.cache;
  const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', v = new Int16Array(128).fill(-1);
  for (let i = 0; i < 64; i++) v[A.charCodeAt(i)] = i;
  const s = GENEVA9_TTF.replace(/=+$/, ''), out = new Uint8Array(Math.floor(s.length * 3 / 4));
  let acc = 0, bits = 0, o = 0;
  for (let i = 0; i < s.length; i++) {
    const d = v[s.charCodeAt(i)];
    if (d < 0) throw new Error('the Geneva font is not base64 at ' + i);
    acc = (acc << 6) | d; bits += 6;
    if (bits >= 8) { bits -= 8; out[o++] = (acc >> bits) & 0xFF; }
  }
  return (geneva9Bytes.cache = out.subarray(0, o));
}
